# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
# The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
# However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, 
# for which their sum and difference are pentagonal and D = |Pk − Pj| 
# is minimised; what is the value of D?

# Fill a list with pentagonal numbers:
penatagonalNumbers = [x*(3*x-1)/2 for x in range (1, 3000)]
nums = []

if __name__ == "__main__":
    for i in range(len(penatagonalNumbers)):
        for t in range(i, len(penatagonalNumbers)):
            difference = penatagonalNumbers[t] - penatagonalNumbers[i]
            addition = penatagonalNumbers[t] + penatagonalNumbers[i]
            if (difference in penatagonalNumbers) and (addition in penatagonalNumbers):
                print(difference)
