
/**
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 
 * + 7 = 28. The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors?
 * 
 */

 function numDivisors(num) {
     var numDivis = 0
     for(var x = 0; x <= num; x++)
        if(num%x === 0)
            numDivis++
    return numDivis
 }

 var numberOfDivisors = 0
 var nthTriangle = 0
 var triangleNumber = 0
 var greatestNumberDivisors = 0

 while(numberOfDivisors < 500){
     nthTriangle++
     triangleNumber += nthTriangle
     numberOfDivisors = numDivisors(triangleNumber)
     if(numberOfDivisors > greatestNumberDivisors){
        greatestNumberDivisors = numberOfDivisors
        console.log("Max divisors: " + greatestNumberDivisors)
     }
        
 }

 console.log(triangleNumber)
 console.log(numberOfDivisors)


