# Triangle, pentagonal, and hexagonal numbers are generated by 
# the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

from math import sqrt

def findRoot(a, b, c, sign):
    if sign:
        return (-b + sqrt(b ** 2 - 4*a*c)) / (2 * a)
    return (-b - sqrt(b ** 2 - 4*a*c)) / (2 * a)

def isPentagonal(num):
    if findRoot(3/2, -1/2, -num, True).is_integer() and findRoot(3/2, -1/2, -num, False).is_integer:
        return True
    return False

def isHexagonal(num):
    if findRoot(2, -1, -num, True).is_integer() and findRoot(2, -1, -num, False).is_integer:
        return True
    return False

if __name__ == "__main__":
    triangleNumbers = [x*(x+1)/2 for x in range(1, 100000)]
    for i in triangleNumbers:
        if isHexagonal(i) and isPentagonal(i):
            print(i)